### ISSUE TITLE
X and Y coordinate list

### ISSUE THREAD

**Issue by sonnyk22** [maurizzzio/function-plot#16]
This feature request is related to #13, but this time I have some images to explain my question better.  #13 is a great solution to get a single clicked-on coordinate. 

Lets imagine a Function graph for Tan(x):
![tan x -graph](https://cloud.githubusercontent.com/assets/6744710/8877632/4663d82a-31f4-11e5-8f04-2e2325c19706.png)

Is there a possibility to add a new feature (if one its not there already) to get a list of all the plotted coordinates (x, y) for the graph above (Function, Polar, and Parametric).  For example:

![tan x -coordinates](https://cloud.githubusercontent.com/assets/6744710/8877871/ed53237e-31f5-11e5-890f-cca5b963a9d9.png)

**Comment by maurizzzio** [comment]
mmm well the problem is that `function-plot` works on top of interval arithmetic which means that what you see on the graph is actually a collection of segments instead of a single point, have a look at this example where you can change the number of samples with a slider

http://jsbin.com/godejunefe/edit?output

therefore I can publish an event describing the rectangles sampled e.g.

```
segment[i] = [[x_low, x_hi], [y_lo, y_hi]]
```

if you use mathjs as the sampler then you'll receive normal points, I'll try to implement tonight

**Comment by maurizzzio** [comment]
as of v1.6.1 you can listen the event `eval`, the callback params are `data` (an array of segment/points),
`index` (the index of datum in the `data` array), `isHelper` (true if the data is created for a helper e.g.
for the derivative/secant)

```javascript
var instance = functionPlot({
  target: '#playground',
  data: [
    { fn: 'sin(exp(x))' },
    { fn: 'tan(x)', graphOptions: {sampler: 'mathjs', type: 'line'} }
  ]
})
instance.on('eval', function (data, i, isHelper) {
  if (!isHelper) {
    console.log(data, i)
  }
})
```

**Comment by sonnyk22** [comment]
thank you
