### ISSUE TITLE
Getting the X, Y coordinates when plotted line is mouse-clicked

### ISSUE THREAD

**Issue by sonnyk22** [maurizzzio/function-plot#26]
Currently, the FP library has 2 events that I know of which will bring back a X, Y coordinates (#19), and the other one will provide the full plotted line coordinates (#16), as shown below.  The solution #19 is providing continuous data as I move my mouse on a plotted line. 

_graphInstance.on('eval', function (data, i, isHelper) {
    // code
});

_graphInstance.on('tip:update', function (x, y, index) {
    // code
})

Is there an event that will bring back the x, y coordinates of the location on a plotted line when it is ONLY mouse-clicked on? Would be great if this could apply to any plotted lines (multi-plot).

**Comment by maurizzzio** [comment]
I've updated the README file with code that can help you find the evaluated data at some `x` value, what you need to do is listen for the click event on the canvas and evaluate the functions you want with the mouse `x` coordinate

**Comment by sonnyk22** [comment]
By chance, do you happen to have a small sample code to that is able to listen the click event on the canvas which returns the coordinates?

**Comment by maurizzzio** [comment]
I did something similar on mousemove, perhaps you can do

```javascript
var el = instance.root.select('rect.zoom-and-drag')
el.on('click', function () {
  var mouse = d3.mouse(el.node())
  var x = instance.meta.xScale.invert(mouse[0])
  var y = instance.meta.yScale.invert(mouse[1])
})
```

**Comment by sonnyk22** [comment]
It worked great!  Thank you!

**Comment by Kallaway** [comment]
@maurizzzio First of all, thank you so much for this beautiful library! 

My issue with the code above is that it works in that it's getting the X and Y coordinates of the mouse at the moment of a click, but I am yet not able to get the coordinates of the point on the line (the ones that are shown on the legend on the top right) 

I can probably scrape the value of Y at the given X (because X wouldn't change) to get the value of Y at this vertical line where it intersects the plotted function, however - is there a more elegant way to do that?

Meaning, is there a way to plug in a certain value of X, just using code (no visualization) into the formula for the function, and to get the real Y?

Like, if x is 25, then just plug that value somewhere to get the y, programmatically. 

Thank you so much in advance!

<img width="521" alt="screen shot 2016-02-03 at 3 55 50 pm" src="https://cloud.githubusercontent.com/assets/8016212/12796805/b4027cdc-ca8e-11e5-9e0f-0a123495d8c7.png">

**Comment by Kallaway** [comment]
@maurizzzio Sorry, already solved! Found it in the documentation - sorry for the question!

**Comment by Kallaway** [comment]
@maurizzzio I have a follow up question. :) When you give this recipe: Evaluate a function at some value x, it works, but is there a way to get to X knowing Y programmatically? Thank you so much in advance!

**Comment by maurizzzio** [comment]
@Kallaway sorry for my late reply, I've been sick the last month and I'm finally recovering

For the example above that involves solving `y = x^2` in terms of `x` which has the solutions `x_1 = sqrt(4y) / 2` and `x_2 = -sqrt(4y) / 2` e.g. when `y = 4; x_1 = 2; x_2 = -2`, now this one has a simple solution however imagine trying to solve `y = 1/x + x^2 - log(x)`, unfortunately this kind of question has a solution which is outside the scope of function plot
