### ISSUE TITLE
API or documentation for specifying the color of text, axis, etc.

### ISSUE THREAD

**Issue by Frodojj** [maurizzzio/function-plot#40]
Using function-plot with a dark background causes the axis and associated text on a graph to be unreadable. An API or documentation on how to override the default text color and axis color would be very useful.

Thank you for writing function-plot! It is a useful library.

**Comment by maurizzzio** [comment]
I've added a section in the README regarding the selectors to style some elements, it requires previous knowledge on how to use stylesheets and some lecture about svg node properties that can be styled

For example to change the color of the text of the x-axis you need to add the following to your stylesheet

```css
.function-plot .x.axis .tick text {
  fill: red !important;
}
```

Note that it's `fill` and not `color` (because the properties for svg dom are different from the regular dom)

You can read more about these attributes here: [`<text>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text), [`<path>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/path), [`<line>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/line)

**Comment by Frodojj** [comment]
Thank you! That is very helpful!
