### ISSUE TITLE
Bug plotting root functions

### ISSUE THREAD

**Issue by iforwms** [maurizzzio/function-plot#48]
Hi,

Plotting ````f(x) = x^(1/2)```` or ````f(x) = x^(1/3)```` does not produce the correct graph. For ````f(x) = x^(1/2)```` there are no solutions for minus x but they are plotted. Also for ````f(x) = x^(1/3)```` all solutions for x below zero should be negative, not positive.

![sqrt x](https://cloud.githubusercontent.com/assets/10304616/11676579/9c53b3e0-9e6e-11e5-8a69-d22a15354f20.PNG)
**Function-plot - f(x) = x^(1/2)**

![sqrt x -correct](https://cloud.githubusercontent.com/assets/10304616/11676644/5cd2de8e-9e6f-11e5-8188-5d28e0f3f050.PNG)
**Correct - f(x) = x^(1/2)**

![cube-rt x](https://cloud.githubusercontent.com/assets/10304616/11676599/d87ad178-9e6e-11e5-8f14-f4033a4611c3.PNG)
**Function-plot - f(x) = x^(1/3)**

![cube-rt x -correct](https://cloud.githubusercontent.com/assets/10304616/11676645/5cd37e0c-9e6f-11e5-8ef5-2a0f482cf636.PNG)
**Correct - f(x) = x^(1/3)**

**Comment by maurizzzio** [comment]
Thanks for the report! I'll solve it on the interval arithmetic package https://github.com/maurizzzio/interval-arithmetic/issues/3

**Comment by maurizzzio** [comment]
Identifying if the exponent plots something in the negative x-axis is quite a challenging problem, I've seen that supercalc (google's plot) actually analyzes the expression to be evaluated and sees if the denominator is even to plot stuff in the negative x-axis (e.g. [`y = x^(1 / 3)`](https://www.google.com.bo/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#q=y+%3D+x%5E(1%2F3))) however since this is an static analysis it doesn't handle cases like [`y = x^(1 / 3 + 0)`](https://www.google.com.bo/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#q=y%20%3D%20x%5E(1%2F3%20%2B%200)&es_th=1)

Doing such a complex static analysis of the expression's ast is quite complex, so I've created a function in interval arithmetic called `nthRoot` (also available in math.js), what you can do to plot roots is use that function instead

e.g. `y = x^(2/3)` needs to be plotted with `nthRoot`

```js
functionPlot({
  target: '#root-finding',
  data: [{
    fn: 'nthRoot(x, 3)^2'
  }]
})
```
