### ISSUE TITLE
how do i do floor(x) ?

### ISSUE THREAD

**Issue by rokyed** [maurizzzio/function-plot#52]
Thank you very much for helping. I can't do floor(x) and i am wondering. Also where can I find the complete list of the things i can do in a plot?

**Comment by maurizzzio** [comment]
Thanks for the question! function-plot evaluates each item of the `data` array as follows

- Check the type of graph to plot (set in the `graphType` option)
  - if it's `interval` then the package [interval-arithmetic is used](https://github.com/maurizzzio/interval-arithmetic)
  - if it's `polyline|scatter` then function-plot checks the presence of library mathjs and uses it if available otherwise it fallbacks to the [built in](https://github.com/maurizzzio/built-in-math-eval) package which is like JS' `Math` with [additional functions](https://github.com/maurizzzio/built-in-math-eval/blob/master/lib/adapter.js)
- Any function defined in any of the libraries above is available to function-plot (without the namespace) so you should check out their available functions

Now to your question regarding `floor(x)`, you'll see that the interval library doesn't have it (not implemented yet) however both mathjs and the fallback library have them, so you could do:

```js
functionPlot({
  target: '#demo',
  data: [{
    fn: 'floor(x)',
    graphType: 'polyline'
  }]
})
```

Note that the `graphType: 'polyline'` forces function-plot to use either mathjs or the one defined in the [built in](https://github.com/maurizzzio/built-in-math-eval) package

**Comment by rokyed** [comment]
thanks
