### ISSUE TITLE
Is it possible to plot an exponential function?

### ISSUE THREAD

**Issue by Kallaway** [maurizzzio/function-plot#54]
Hi @maurizzzio , I was trying to plot an exponential function, with simple: fn: '1^x' , but for me it doesn't work. What am I doing wrong, could you please help? Is it possible to do with function-plot? Thank you!

**Comment by Kallaway** [comment]
@sonnyk22 could you please help if you can? I've noticed that you've used the library quite extensively :)

**Comment by Kallaway** [comment]
Figured it out - turned out it was a syntax problem on my end. This helped: https://github.com/maurizzzio/function-plot/issues/10

So, basically, instead of fn: '1^x' I should have done fn: 'pow(x, 1)' and that's it.

Is there somewhere a full documentation on this syntax, or is it just JS Math library integrated so that there is no need to type Math.pow()?

**Comment by sonnyk22** [comment]
Sorry for my late reply.  I believe Function-Plot uses MathJS lib (http://mathjs.org/) which is a very powerful library.  If you have any related question, you can reach out to them as well.

**Comment by maurizzzio** [comment]
@Kallaway sorry for my late reply, I've been sick the last month and I'm finally recovering

I believe I wrote this somewhere on the examples/readme but function-plot has 2 ways to sample a function

- the traditional way e.g. for a given `f(x)` the samples are computed by evaluating `f(x)` with `x = a_1, a_2, ..., a_n` , where `n` is given by the option `samples` and  `a_1` being the left endpoint shown currently on the viewport and `a_n` the right endpoint shown on the viewport, note that `a_i` is a single number
- interval sampling e.g. for a given `f(x)` the samples are computed by evaluating `f(x)` with `x = [a_11, a_12], [a_21, a_22], ..., [a_n1, a_n2]`, note that now the samples are pairs of two numbers instead of a single number

By default the interval sampler is used however some operations aren't implemented yet on the [interval arithmetic](https://github.com/maurizzzio/interval-arithmetic) package, one of them is computing `a^x` where `x` is an interval (as of now it computes `a^x` where `a` is an interval and  `x` is a single number e.g. `[2, 3]^2 = [4, 9]`)

Now coming back to your problem you want to compute `1^x` which in interval arithmetic is like `[1, 1]^[x_1, x_2]`, unfortunately it's not implemented yet because of the underlaying complexity however the operation is available in the traditional sampler, so you can use that instead e.g.

```js
functionPlot({
  target: '#demo',
  data: [{
    fn: '1^x',
    graphType: 'polyline'
  }]
})
```

So the following combinations are available as of now

- (default) `{ graphType: 'interval' }` which uses the interval sampler (`{ sampler: 'interval' }` internally)
- `{ graphType: 'polyline' }` which uses the traditional sampler (`{ sampler: 'builtIn' }` internally)
- `{ graphType: 'scatter' }` which uses the traditional sampler (`{ sampler: 'builtIn' }` internally)

Note that `pow(x, 1)` is not equal to `1^x` it's actually `x^1` which is available in the interval sampler
