### ISSUE TITLE
Can the axis points be shown in radians or degrees?

### ISSUE THREAD

**Issue by Kallaway** [maurizzzio/function-plot#56]
Hi @maurizzzio ! Thank you so much for helping me out previously! There is another question that came up during my experiments. I am trying to plot a sine wave and I want to show the axis points in degrees or/and radians, but I couldn't find a way to do that yet. Is there a possibility of this? 

Thank you so much!
Alex

**Comment by maurizzzio** [comment]
Right out of the box there's no way unfortunately however I'm sure it's possible!, since this is built on top of d3's `d3.svg.axis` which in turn uses [a scale to determine the axis points (which are called `ticks` in d3)](https://github.com/mbostock/d3/blob/master/src/svg/axis.js#L29-L30) you can define your own scale just like `d3.scale.linear` to fulfill your needs

I'd do this:

- Define a new 'degree' or 'rad' scale, you can see [linear scale](https://github.com/mbostock/d3/blob/master/src/scale/linear.js) or [log scale]() for further info
- [Modify the way the ticks are computed](https://github.com/mbostock/d3/blob/master/src/scale/linear.js#L117) so that it shows depending on the domain ticks at [30 deg, 60 deg, ...] or something similar
- Attach it to d3 global namespace i.e. `d3.scale.degrees = my own scale `
- Tell function-plot to use that scale e.g.

```js
functionPlot({
  ...
  xAxis: {
    type: 'degrees'
  }
  ...
})
```

**Comment by Kallaway** [comment]
Thank you for getting back to me so quickly! I will do my best to implement the solution you've suggested!
