### ISSUE TITLE
Polynomial functions with even and odd powers renders thick sections

### ISSUE THREAD

**Issue by JSHARP-** [maurizzzio/function-plot#61]
Hi @maurizzzio,

I have noticed that the interval arithmetic rendering you have employed will produce interesting results when the expression is a polynomial with even AND odd orders.

![polynomial](https://cloud.githubusercontent.com/assets/1894595/14194670/4b3e8378-f76e-11e5-977a-85e3d3317ecc.png)

![screen shot 2016-03-31 at 6 28 06 pm](https://cloud.githubusercontent.com/assets/1894595/14194675/57305c42-f76e-11e5-9445-90c3f815197e.png)

If I plot a polynomial function with multiple terms that have odd _n_ and even _n_ the plotter renders these very thick sections. 

Example 1:

![screen shot 2016-03-31 at 6 27 24 pm](https://cloud.githubusercontent.com/assets/1894595/14194720/b2f196d6-f76e-11e5-9e41-390ade20d142.png)

If the _n_ values are all odd, or all even, the plot is fine.

Example 2 (ALL ODD):

![screen shot 2016-03-31 at 6 34 36 pm](https://cloud.githubusercontent.com/assets/1894595/14194776/40a8c800-f76f-11e5-8091-40a978c26849.png)

Example 3 (ALL EVEN):

![screen shot 2016-03-31 at 6 33 36 pm](https://cloud.githubusercontent.com/assets/1894595/14194764/1da224e6-f76f-11e5-8ff3-f1e9d838af72.png)

But as soon as you combine even AND odd _n_ values, it renders the thick sections.

![screen shot 2016-03-31 at 6 09 20 pm](https://cloud.githubusercontent.com/assets/1894595/14194443/df8bcd5e-f76b-11e5-9bb0-1a68547dbe9e.png)

My suspicion is that the even order polynomials have only positive results. So perhaps, when the slopes are descending, the interval math will compound the intervals into one that is bigger than it should be? I could be completely wrong, but it's a hunch.

Any feedback would be appreciated. This seems like an interesting math problem! 

Thanks.

**Comment by maurizzzio** [comment]
Thanks for the question, what you're seeing is one of the drawbacks of using interval arithmetic which is that due to some operations an interval is representing more values than it should but first let me give you a counterexample to your conjecture that also presents this problem

[`x^3 - 5x`](http://jsbin.com/zokare/edit?html,js,output)

Now going back to the problem let's analyze the simpler function `x^2 + kx` where `k` is a real number, when the function is evaluated with interval arithmetic internally it'll be translated to code like [this one](http://esnextb.in/?gist=ea0165640e82a7a230520648b63589e3) and executed with different range of values e.g. `[2.50, 2.51]` however as you see in the gist the results vary depending on the range even though the range width is the same for all values, for the example above one of the problems lies in the `kx` factor, imagine that `x = [2.50, 2.51]` then `5x = [12.50, 12.55]` the first observation is that the interval is now considering more values than before (5 times the width of the range) so `kx` will consider values k times the width of a range, this propagation of additional values is because of the nature of intervals and interval arithmetic

There are 3 possible solutions for this problem:

- increase the number of samples so that the propagation of values is minimized (implemented)

```js
functionPlot({
  target: '#playground',
  data: [{
    fn: 'x^2 + 5x',
    nSamples: 7000
  }]
})
```

- change the sampler to use normal math (implemented)

```js
functionPlot({
  target: '#playground',
  data: [{
    fn: 'x^2 + 2x',
    sampler: 'builtIn',
    graphType: 'polyline'
  }]
})
```

- use interval arithmetic altogether other advanced techniques to render a true graph (not implemented yet)

Additional graphs that fail:

- [`sin(x)/x` with intervals](http://jsbin.com/kavizoj/edit?html,js,output)
- [`sin(x)/x` without intervals](http://jsbin.com/fitume/edit?html,js,output)

**Comment by sorawee** [comment]
Can you describe more about the "advanced techniques"? Are you referring to Tupper's paper?

**Comment by maurizzzio** [comment]
I think http://dl.acm.org/citation.cfm?id=143314 is the paper, I haven't read it yet but it's mentioned on http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.45.4623&rep=rep1&type=pdf which says:

> As suggested in [Fat92], honest plotting should be used together with other techniques for getting a true figure of a curve or surface.

**Comment by JSHARP-** [comment]
Thank you @maurizzzio, this helps a lot.
