### ISSUE TITLE
Vector fields? 

### ISSUE THREAD

**Issue by omrihar** [maurizzzio/function-plot#68]
I just discovered your library and I find it really great! I just browsed the documentation and tried out some examples so far and was wondering whether it's possible to draw vector fields using your library?
So far I haven't seen it in my browsings. I think it will be an awesome feature to add if it's not yet possible.

Thanks!
Omri

**Comment by maurizzzio** [comment]
Thanks for the feature request, unfortunately functionPlot is not able to draw vector fields however many people started using this library and it seems that most of its functionality should be modularized to allow other devs to include any functionality they need with little effort

However functionPlot is able to draw a single vector with the following syntax (taken from the main page)

```js
functionPlot({
  target: '#vector',
  xAxis: {domain: [-3, 8]},
  grid: true,
  data: [{
    vector: [2, 1],
    offset: [1, 2],
    graphType: 'polyline',
    fnType: 'vector'
  }]
})
```

Given the following vector field `F(x, y) = -y i  + x j` where `i = [1 0]` and `j = [0 1]` we can sketch all the vectors with integer coordinates in the box with `[-3, -3]` as the bottom left end and `[3 3]` as the top right by evaluating `F(x,y)` with all the integers `x,y` that belong to the box, in JS that'd be

```js
function F(x, y) {
  return [-y, x]
}

var data = []
for (var i = -3; i <= 3; i += 1) {
  for (var j = -3; j <= 3; j += 1) {
    var [x, y] = F(i, j)
    var offset = [i, j]
  }
}
```

This data would be then fed to function plot as follows 

[demo](http://jsbin.com/levuxelagi/1/edit?html,js,output)

It'd be awesome to have this done by function plot automatically e.g.

```js
functionPlot({
  target: '#vector',
  xAxis: {domain: [-3, 8]},
  grid: true,
  data: [{
    f: '-y * i + x * j',   
    fnType: 'vector-field'
  }]
})
```

As I've told in the first paragraph, I'm thinking about modularizing this project so that the above becomes

```js
var f = require('function-plot')
var vf = require(fp-vector-field)

var chart = f({ /* options */})
var myField = vf({
  f: '-y * i + x * j'
})
chart.add(myField)
```

**Comment by omrihar** [comment]
Hi, thanks for the detailed and quick reply! Indeed I've noticed the vector plot type but that's why I was wondering whether there is a vector-field option that I missed somehow.
I'm not an expert on javascript library development but it does indeed sound logical to make it easy to contribute to so the project is not dependent on a small set of developers who understand everything (given that this modularization comes with documentation on how to extend the project ;-)).

Thanks again for the great project and reply! I plan to use it for some blog posts I want to write and that might require plots of functions and vector fields, so I just add a code snippet in the middle of my markdown file like this:

```html
<div id="my_chart"></div>
<script type="text/javascript">
// generate chart here
</script>
```

and a plot will appear. Already tested this and apart from the requirement of having to load function-plotter in the `<head>` section of my site instead of at the end of the `<body>` part, it works flawlessly.

Cheers,
Omri
