### ISSUE TITLE
Strange behavior when plotting functions with undefined points

### ISSUE THREAD

**Issue by fkuteken** [maurizzzio/function-plot#87]
Hello,
Something strange happens when I try plotting a function with an undefined point.
An example of this is f(x) = sin(1 / x):
<img width="568" alt="captura de tela 2017-02-06 as 15 56 46" src="https://cloud.githubusercontent.com/assets/20425131/22659478/e428a35a-ec84-11e6-933f-2002e2a3f23a.png">

Another example would be f(x) = (x - 1) / (x^2 - 1).
Is there any way I can avoid this issue?
Thanks in advance.

**Comment by maurizzzio** [comment]
This is because the use of interval arithmetic, when functions are evaluated with this strategy the result is *ensured to contain all the points that belong to your function*, unfortunately for some functions you get results like this because the correlation between the numerator and the denominator is not taken into account when the function is evaluated (yielding in higher interval results)

The image you attached belongs to `sin(x)/x` which has this problem

http://jsbin.com/notuziziba/1/edit?html,js,output

Unfortunately unless more work is put into the interval arithmetic evaluator this issue will exist for *some functions (particularly the ones involving division)*, in any case you can use the normal evaluator as follows

```js
functionPlot({
  target: '#demo',
  data: [{
    fn: 'sin(x)/x',
    graphType: 'polyline',
    sampler: 'builtIn'
  }]
});
```

http://jsbin.com/jiqiquguma/1/edit?html,js,output

**Comment by fkuteken** [comment]
Thanks for the response, using the graphType as a polyline worked well.
Still in the topic of plotting functions with undefined points, I tried using another data set containing these points and used the graphType as scatter, but the points are really small. Is there any way to change the points' radius and make them standout more?
Here is an example:

http://jsbin.com/qoxijocota/1/edit?html,js,output
```javascript
functionPlot({
  target: '#demo',
  data: [
    {
      fn: 'sin(x)/x',
      graphType: 'polyline',
      color: 'steelblue'
    },
    {
      points: [[0, 1]],
      fnType: 'points',
      graphType: 'scatter',
      color: 'steelblue'
    }
  ]
});
```

**Comment by maurizzzio** [comment]
Yep, use a stylesheet with the following selector

```css
.function-plot .canvas .content circle {
  r: 5;
}
```
