### ISSUE TITLE
stroke-dasharray usage

### ISSUE THREAD

**Issue by si14** [maurizzzio/function-plot#91]
Hi there!

I was trying to plot a simple function with a dashed line, but failed. Here is the code:

```javascript
functionPlot({
  target: '#demo',
  data: [{
    fn: 'x^2',
    color: 'red',
    attr: {
      'stroke-dasharray': '0.1,0.5' 
    }
  }]
});
```

Here is how it looks like:

<img width="236" alt="screen shot 2017-04-23 at 13 52 49" src="https://cloud.githubusercontent.com/assets/316910/25313731/9e16c4bc-282c-11e7-8d60-da050c0ae0e8.png">

Dashes are very small (which can be expected given the arguments to the `stroke-dasharray`) and irregular (which isn't expected). When I try to make them longer, dashes disappear completely. I don't fully understand SVG paths, but it looks like that's because of the way the path is specified.

Do you think it's possible to make a dashed plot? It's very useful for printing stuff out in grayscale.

**Comment by maurizzzio** [comment]
Yep, the problem is that this library uses interval arithmetic by default to evaluate functions and its renderer works by rendering a lot of rectangles instead of connecting lines as you would expect.

This problem is not present with the other renderer which you can trigger with `graphType: polyline`, refer to the docs/examples for more info on the differences between them

```javascript
functionPlot({
  target: '#demo',
  data: [{
    fn: 'x^2',
    color: 'red',
    graphType: 'polyline',
    attr: {
      'stroke-dasharray': '5, 5' 
    }
  }]
});
```

**Comment by si14** [comment]
Ah, I get it! Thanks a lot :)
