### ISSUE TITLE
Custom variable names in equations

### ISSUE THREAD

**Issue by zaplachinsky** [maurizzzio/function-plot#93]
Hi @maurizzzio, thanks for very useful library!

I watched all previous issues and read all documentation, but I don't found and I don't understand how can I replace the predefined variable names (`theta` for polar equation or `x` for linear equation etc.).

Let's say, I want the input to be `2cos(a)` instead of `2cos(theta)`. I know how to define additional variables for equation via `scope` object, but it's not working for me there.

Thanks!

**Comment by maurizzzio** [comment]
Unfortunately for some functions the variables to be used are already define e.g. for [polar equations the variable used is `theta`](https://github.com/maurizzzio/function-plot/blob/v1.17.1/lib/samplers/builtIn.js#L146), if you want to use other variables in the definition you can always use a function instead of a string e.g.

```javascript
functionPlot({
  target: '#demo',
  yAxis: {domain: [-1.897959183, 1.897959183]},
  xAxis: {domain: [-3, 3]},
  data: [{
    r: function (scope) {
      const r0 = 0
      const a = 0.5
      const gamma = 0
      const theta = scope.theta
      return r0 * Math.cos(theta - gamma) +
        Math.sqrt(a * a - r0 * r0 * Math.pow(Math.sin(theta - gamma), 2))
    },
//    r: 'r0 * cos(theta - gamma) + sqrt(a^2 - r0^2 * (sin(theta - gamma))^2)',
    fnType: 'polar',
    graphType: 'polyline'
  }]
})
```

**Comment by zaplachinsky** [comment]
Okay, now it's clear for me.

Thanks for reply!)
